######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 18 23:22:09 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyWidget.h
SOURCES += main.cpp MyWidget.cpp
