######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 19 10:37:20 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyWidget.h
SOURCES += main.cpp MyWidget.cpp
