######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 22 09:50:06 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyTextEdit.h MyWidget.h
SOURCES += main.cpp MyTextEdit.cpp MyWidget.cpp
